# Generated by Django 4.0.3 on 2022-04-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
