# Generated by Django 4.0.3 on 2022-04-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='assignee_user_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='autor_user_id',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='project_id',
            new_name='project',
        ),
    ]
