# Generated by Django 4.0.3 on 2022-04-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_assignee_user_id_issues_assignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='project',
            new_name='project_id',
        ),
    ]
