# Generated by Django 4.0.3 on 2022-04-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_author_user_id_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='autor',
            new_name='author',
        ),
    ]
