# Generated by Django 4.0.3 on 2022-04-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_autor_issues_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='project_id',
            new_name='project',
        ),
    ]
